// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tftWEB.Models;

namespace tftWEB.Migrations
{
    [DbContext(typeof(TFTContext))]
    [Migration("20190701213303_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("tftWEB.Models.Champion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ClassId");

                    b.Property<string>("Description");

                    b.Property<int>("Gold");

                    b.Property<string>("IconUrl");

                    b.Property<int?>("OriginId");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("OriginId");

                    b.ToTable("Champions");
                });

            modelBuilder.Entity("tftWEB.Models.ChampionClass", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int>("Count");

                    b.Property<string>("Description");

                    b.Property<string>("GeneralDescription");

                    b.HasKey("Id");

                    b.ToTable("ChampionClass");
                });

            modelBuilder.Entity("tftWEB.Models.ChampionOrigin", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int>("Count");

                    b.Property<string>("Description");

                    b.Property<string>("GeneralDescription");

                    b.HasKey("Id");

                    b.ToTable("ChampionOrigin");
                });

            modelBuilder.Entity("tftWEB.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("IconUrl");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("tftWEB.Models.ItemRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("NextItemId");

                    b.Property<int?>("PreviousItem1Id");

                    b.Property<int?>("PreviousItem2Id");

                    b.HasKey("Id");

                    b.HasIndex("NextItemId");

                    b.HasIndex("PreviousItem1Id");

                    b.HasIndex("PreviousItem2Id");

                    b.ToTable("ItemRelations");
                });

            modelBuilder.Entity("tftWEB.Models.Champion", b =>
                {
                    b.HasOne("tftWEB.Models.ChampionClass", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId");

                    b.HasOne("tftWEB.Models.ChampionOrigin", "Origin")
                        .WithMany()
                        .HasForeignKey("OriginId");
                });

            modelBuilder.Entity("tftWEB.Models.ItemRelation", b =>
                {
                    b.HasOne("tftWEB.Models.Item", "NextItem")
                        .WithMany()
                        .HasForeignKey("NextItemId");

                    b.HasOne("tftWEB.Models.Item", "PreviousItem1")
                        .WithMany()
                        .HasForeignKey("PreviousItem1Id");

                    b.HasOne("tftWEB.Models.Item", "PreviousItem2")
                        .WithMany()
                        .HasForeignKey("PreviousItem2Id");
                });
#pragma warning restore 612, 618
        }
    }
}
